#ifndef CONFIG_H_
#define CONFIG_H_

// common
#define VERSION "0.1"

#define CYCLE_TIME_MS 4U
#define CYCLE_TIME_US (CYCLE_TIME_MS * 1000U)

#define MEASUREMENT_MODE

// on-board LEDs
#define INTERNAL_LED_GPIO 13U
#define RED_LED_GPIO 5U
#define GREEN_LED_GPIO 6U

// controller receiver
#define MAX_RECEIVER_CHANNELS 10U
#define RECEIVER_PIN 14U

#define CHANNEL_ROLL 0U
#define CHANNEL_PITCH 1U
#define CHANNEL_THROTTLE 2U
#define CHANNEL_YAW 3U
#define CHANNEL_SWITCH_EMERGENCY 7U

// voltage measurement
#define ADC_INPUT_RESOLUTION_BITS 10U
#define BATTERY_VOLTAGE_INPUT_PIN 15U

#define BATTERY_VOLTAGE_DIVIDER_RATIO 5U
#define BATTERY_CURRENT_DIVIDER_RATIO 0.036F

// current measurement
#define BATTERY_CURRENT_INPUT_PIN 21U

// I2C config
#define I2C_FREQ_IN_HZ 400000U
#define MCP6050_BUS_ID 0x68U

// UART config
#define SERIAL_BAUDRATE 57600L

// Motor controllers
#define ESC_INPUT_FREQ_HZ 250U
#define MOTOR_FR_PIN 1U
#define MOTOR_RR_PIN 2U
#define MOTOR_RL_PIN 3U
#define MOTOR_FL_PIN 4U

// Safety features
#define RECVR_DISCONNECT_TIMEOUT_MS 500U
#define RECVR_DISCONNECT_TIMEOUT_US (RECVR_DISCONNECT_TIMEOUT_MS * 1000U)

#endif /* CONFIG_H_ */